// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSbfrr_34xTp9BsS-lKL1D4QT3GC28r2A',
    appId: '1:241961480287:web:ec8c45d4dd7c0d91176bea',
    messagingSenderId: '241961480287',
    projectId: 'signin-64eff',
    authDomain: 'signin-64eff.firebaseapp.com',
    storageBucket: 'signin-64eff.firebasestorage.app',
    measurementId: 'G-MKTL838E8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrvSZfCI-ZoWgyfz5XRpzRV9a-5iNl3I',
    appId: '1:241961480287:android:d02c210a5536a196176bea',
    messagingSenderId: '241961480287',
    projectId: 'signin-64eff',
    storageBucket: 'signin-64eff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl_kpNZ59tRjbn06QZNIvlRGUfUvxKFb8',
    appId: '1:241961480287:ios:6aea0da583158785176bea',
    messagingSenderId: '241961480287',
    projectId: 'signin-64eff',
    storageBucket: 'signin-64eff.firebasestorage.app',
    iosBundleId: 'com.example.hiveSheredPref',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl_kpNZ59tRjbn06QZNIvlRGUfUvxKFb8',
    appId: '1:241961480287:ios:6aea0da583158785176bea',
    messagingSenderId: '241961480287',
    projectId: 'signin-64eff',
    storageBucket: 'signin-64eff.firebasestorage.app',
    iosBundleId: 'com.example.hiveSheredPref',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSbfrr_34xTp9BsS-lKL1D4QT3GC28r2A',
    appId: '1:241961480287:web:ce363090d5269f0b176bea',
    messagingSenderId: '241961480287',
    projectId: 'signin-64eff',
    authDomain: 'signin-64eff.firebaseapp.com',
    storageBucket: 'signin-64eff.firebasestorage.app',
    measurementId: 'G-N7XTL0KKQS',
  );
}
